spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3307/db
    username: sa
    password: password

  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: false
    hibernate:
      ddl-auto: create-drop

  sql:
    init:
      mode: always