spring:
  kafka:
    bootstrap-servers: localhost:9094

  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: sa
    password: password

  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: false
    hibernate:
      ddl-auto: create-drop

  sql:
    init:
      mode: always

user-service:
  address: localhost
  grpc:
    port: 9001

