version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
      nodejs: 16
    commands:
      - npm install -g aws-cdk-lib
      - npm install -g aws-cdk

  pre_build:
    commands:
      - echo Pre-build phase started on `date`

  build:
    commands:
      - echo Build started on `date`
      - cd infrastructure
      - mvn clean install
      - cd ..
      - npx cdk synth

artifacts:
  base-directory: infrastructure/cdk.out
  files:
    - '**/*'